module.exports = {
  apps: [
    {
      name: 'gun-relay',
      script: './gun-relay/gun-relay-enhanced.js',
      cwd: '/var/www/interpoll',
      interpreter: 'node',
      env: {
        PORT: 8765,
        NODE_ENV: 'production',
        MYSQL_HOST: process.env.MYSQL_HOST || '127.0.0.1',
        MYSQL_USER: process.env.MYSQL_USER || '',
        MYSQL_PASSWORD: process.env.MYSQL_PASSWORD || '',
        MYSQL_DATABASE: process.env.MYSQL_DATABASE || '',
        MYSQL_PORT: process.env.MYSQL_PORT || '3306',
      },
      max_memory_restart: '400M',
      restart_delay: 3000,
      error_file: '/var/log/pm2/gun-relay-error.log',
      out_file: '/var/log/pm2/gun-relay-out.log',
    },
    {
      name: 'relay-server',
      script: './relay-server/relay-server-enhanced.js',
      cwd: '/var/www/interpoll',
      interpreter: 'node',
      env: {
        PORT: 3001,
        NODE_ENV: 'production',
        DOMAIN: process.env.DOMAIN || 'https://endless.sbs',
        FRONTEND_ORIGIN: process.env.FRONTEND_ORIGIN || 'https://endless.sbs',
        MYSQL_HOST: process.env.MYSQL_HOST || '127.0.0.1',
        MYSQL_USER: process.env.MYSQL_USER || '',
        MYSQL_PASSWORD: process.env.MYSQL_PASSWORD || '',
        MYSQL_DATABASE: process.env.MYSQL_DATABASE || '',
        MYSQL_PORT: process.env.MYSQL_PORT || '3306',
        ASSET_JS: process.env.ASSET_JS || '/assets2/index.js',
        ASSET_CSS: process.env.ASSET_CSS || '/assets2/index.css',
      },
      max_memory_restart: '400M',
      restart_delay: 3000,
      error_file: '/var/log/pm2/relay-server-error.log',
      out_file: '/var/log/pm2/relay-server-out.log',
    },
  ],
};
